import './globals.css'
import Navbar from './components/Navbar'



export const metadata = {
  title: 'Unkown Adventures',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter} bg-black">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
